---
title: "Harvard Spring 2021 Course Enrollment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
library(janitor)
```

```{r, File Read-in}
# Making sure  to skip the right number of lines is essential. My data got
# messed up when I didn't have the right skip argument. Cleaning the data is
# REALLY important also cause it'll make the column names much easier to deal
# with. The janitor library needs to be installed prior though!

enrollment <- read_excel("raw_data/class_enrollment_summary_by_term_2-10-2021.xlsx", skip = 3)
enrollment %>%
  clean_names() %>%
  drop_na() %>%
  select(course_title,course_id, course_name, total) -> enrollment_clean
```

```{r}
# Had to look up the reason .groups was necessary, realized its  really needed.
# When using fct_reorder we have to input the y argument twice one in the x and
# one in the y. The names were too long so coord_flipped the axes and that made
# it easier to see the names of the axes.
enrollment_cleaner <- enrollment_clean %>%
  group_by(course_id, course_title, course_name) %>%
  summarise(total = sum(total),
            .groups ="drop") %>%
  arrange(desc(total)) %>%
  slice(1:10)

enrollment_p <- enrollment_cleaner %>%
  ggplot(mapping = aes(x = fct_reorder(course_name, total),
                       y = total,
                       fill = "aliceblue")) +
  guides(fill = FALSE) +
            geom_col() +
  coord_flip() +
  labs(x = "",
       y = "# of Students Enrolled",
       title = "Top 10 Harvard Spring 2021 Student Enrollment",
       subtitle = "Required courses and intro courses dominate",
       caption = "Source: Harvard Registrar, Work By: Fahad Alkhaja") +
  theme_test()

enrollment_p

```

```{r Saving Image, message = FALSE}
ggsave("enrollment.jpg", enrollment_p)
```

